version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./dbdata:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: asubrand
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    links:
      - db
    ports:
      - 8080:8080
    volumes:
        - /sessions
        
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - ./wp-data:/var/www/html # Full wordpress project
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: asubrand
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mysql